### ISSUE TITLE
Search Job on Home Page

### ISSUE THREAD

**Issue by DCLH** [LanchingHub/LH#1]
Currently Search Job on home page is not working.

User can enter keyword to search job. On hit of a search button, user will be redirected to search screen with or without login.

Send proposal button will be visible on Search job page, once user will hit on submit proposal, it will check whether user is logged in or not.

If not logged in, then login page will be displayed. On successful login, system will check whether user is registered as freelancer or employer (Client). Submit proposal is only valid for freelancer only.

If logged In, system will check whether user is registered as freelancer or employer (Client). Submit proposal is only valid for freelancer only.

**Comment by rishabh047** [comment]
@DCLHDEV
Issue 1:
Redirection takes very long time.

Issue2:
Search Job(Home Page without login) > On Search Screen > Click on View Job > View Job page.
Issue: Without login, any user can see proposals. 
Resolution: No Proposal section visible without login. The only client user can see their proposals.  

![image](https://user-images.githubusercontent.com/35635866/35769904-64f74dc6-0938-11e8-9a0d-e0c72e120ec9.png)

**Comment by rishabh047** [comment]
@DCLHDEV Also, when a freelancer goes to Search job page then load all the jobs as default.

**Comment by DCLHDEV** [comment]
Issue 1:
Redirection takes very long time.

This is the exiting issue, I think the existing experienced developer of this project can optimize the code of search page and it will take time as a new task.

**Comment by DCLHDEV** [comment]
Issue2:
Search Job(Home Page without login) > On Search Screen > Click on View Job > View Job page.
Issue: Without login, any user can see proposals.
Resolution: No Proposal section visible without login. The only client user can see their proposals.
==> Done

**Comment by DCLHDEV** [comment]
Rishabh please update this ticket for 
Issue 1:
Redirection takes very long time.
