### ISSUE TITLE
Client Post Login - View Proposal Page

### ISSUE THREAD

**Issue by DCLH** [LanchingHub/LH#12]
Few Bugs found on View Proposal Page

1) Rating Stars are not getting displayed
2) Rating Count is showing wrong
3) Pagination needs to be applied
4) Attachment Section need be removed from Page layout
5) Shortlist, Accept, Decline functionality needs to be re-built.

**Comment by DCLHDEV** [comment]
1 Rating Stars are not getting displayed
==> It is already displayed. Let me know if I am wrong. 
3 Pagination needs to be applied
==> Where it should be applied?
5 Shortlist, Accept, Decline functionality needs to be re-built.
==> I have seen the buttons on right-hand side. please explain these functionalities so I can proceed.

**Comment by DCLHDEV** [comment]
2 Rating Count is showing wrong
==> I have cross-checked with database value it is fine for me.

**Comment by DCLHDEV** [comment]
4 Attachment Section need be removed from Page layout
==>DONE -  Removed the section

**Comment by rishabh047** [comment]
@DCLHDEV 
The page is crashed.
![image](https://user-images.githubusercontent.com/35635866/35770141-d4996d32-093b-11e8-94a6-1e907aa58c88.png)

**Comment by DCLH** [comment]
- Page get crash sometimes.
- If Client select shortlist, other proposal actions should not be disabled. Client can shortlist multiple proposals.
- If Client select Accept, all the proposals are getting accepted which is wrong.
   Ideally, 1 proposal should be accepted and action dropdown of all the proposal should be disabled. Job status should also be set as hired and it should not be visible on search job page.

- If Declined, action dropdown should have no impact, status of proposal will set as decliend and will display on the proposal page again.

- Email notification also required, when accepted, freelancer should get an email that your proposal has been accepted for this Project (Project link required in email body)
- Email notification when decliened, freelancer should get a decline email (Project Link required in email body)

**Comment by DCLHDEV** [comment]
I need to discuss with Rishabh regarding all the above points except the first one which I have did already.

**Comment by DCLHDEV** [comment]
I will give a new estimation of this two task and once you approve I will start work on this. 

1) Email notification also required, when accepted, freelancer should get an email that your proposal has been accepted for this Project (Project link required in email body)

2) Email notification when declined, freelancer should get a decline email (Project Link required in email body)

**Comment by rishabh047** [comment]
Freelancer not able to see their posted proposal.
Previously it's visible.
![image](https://user-images.githubusercontent.com/35635866/36023782-9ddb69b8-0db3-11e8-864b-0a5842fdd7f6.png)

**Comment by rishabh047** [comment]
From Client Login: 
- Accepted Proposal is getting hide from List, but when we again open the job then it is showing.
![image](https://user-images.githubusercontent.com/35635866/36024049-828e5336-0db4-11e8-8d01-22452b614717.png)

**Comment by DCLHDEV** [comment]
@rishabh047, This will be a new task, please explain in details so I will estimate it. 
Freelancer not able to see their posted proposal.
Previously it's visible.

**Comment by DCLHDEV** [comment]
Freelancer not able to see their posted proposal.
Previously it's visible. 
==> Done

From Client Login:
Accepted Proposal is getting hide from List, but when we again open the job then it is showing.
==> I am not able to generate this, please provide me the test cases.

**Comment by rishabh047** [comment]
Fixed.
