### ISSUE TITLE
Search Freelancer on Home Page

### ISSUE THREAD

**Issue by DCLH** [LanchingHub/LH#2]
Currently Search Freelancer on home page is not working.

User can enter keyword to search freelancer. On hit of a search button, user will be redirected to search freelancer screen with or without login.

Invite button will be visible on Search Freelancer page, once user will hit on Invite button it will check whether user is logged in or not.

If not logged in, then login page will be displayed. On successful login, system will check whether user is registered as freelancer or employer (Client). Invite Job is only valid for freelancer only. 

If logged In, system will check whether user is registered as freelancer or employer (Client). Invite for Job only valid for freelancer only. (Remaining flow can be defined later)

**Comment by DCLH** [comment]
User is unable to view the profile detail of Freelancer (Rishabh will help you on this page)
Contact button should be replaced with Login & Contact.
Once User login succesfully.. it should redirect the user to freelancer detail page (Rishabh will help you on that page).

**Comment by DCLHDEV** [comment]
I am not getting this task, I need to talk with Rishabh on call I think.

**Comment by DCLHDEV** [comment]
As we talked Rishabh is going to confirm the work.

"User is unable to view the profile detail of Freelancer (Rishabh will help you on this page)
Contact button should be replaced with Login & Contact.
Once User login successfully.. it should redirect the user to freelancer detail page (Rishabh will help you on that page)."

**Comment by rishabh047** [comment]
@DCLHDEV 
The screen is opening but no data is display. Please check 

![image](https://user-images.githubusercontent.com/35635866/36024788-d063eb6e-0db6-11e8-9f76-2fbd27228b9e.png)

**Comment by DCLHDEV** [comment]
@rishabh047 : please provide the test case.

**Comment by DCLHDEV** [comment]
@DCLHDEV
The screen is opening but no data is display. Please check
==>Done
