### ISSUE TITLE
Post a Job (W/O Login)

### ISSUE THREAD

**Issue by DCLH** [LanchingHub/LH#3]
Currently this functionality exist for logged in user, but does not exist for unregistered user.

New user can post a job without logged into Lanching Hub. Existing Post a job screen will be used with additional fields like 
1). First Name
2) Last Name
3) Email Address
4) Password.

System will perform following functionality. 

1) All fields will be validated Like first name should not be blank, email address should be in right format, password should follow the LH password policy.
2)Check whether user does exist or not in system. If exist, then login link should display to user.
3)After successful validation, user record will be created in LH as Employer/Client. Job will be created with status as "Pending"
4) Email verification link will be sent to employer email id.
5) Once email will get verified, job status will be set as "Published"

**Comment by rishabh047** [comment]
![image](https://user-images.githubusercontent.com/35635866/35770002-c4eb2ff8-0939-11e8-89da-503a063e4972.png)

Below fields should be on top:
1). First Name
2) Last Name
3) Email Address
4) Password.


Like this (Note: below screenshot is just for reference):
![image](https://user-images.githubusercontent.com/35635866/35770011-f6aef510-0939-11e8-9ad4-979c272ab077.png)

**Comment by rishabh047** [comment]
@DCLHDEV 
Sucess or Error message is now not showing on page after Job post(with login).
![image](https://user-images.githubusercontent.com/35635866/35770196-b3e22c7c-093c-11e8-8232-4c030a598a71.png)

**Comment by DCLHDEV** [comment]
Below fields should be on top:
1). First Name
2) Last Name
3) Email Address
4) Password
==> Done

Sucess or Error message is now not showing on page after Job post(with login).
==> Done

**Comment by rishabh047** [comment]
Job Status Is Showing Published without validating Email.

**Comment by DCLHDEV** [comment]
I am sending status "OpenForProposal", let me know which I need to pass. 
        All = 0,
        OpenForProposals = 1,
        WorkInProgress = 2,
        Completed = 3,
        Draft = 4,
        Archived = 5,
        Withdrawn = 6

**Comment by DCLHDEV** [comment]
As discuss with @rishabh047 I am passing now Draft = 4 instead of OpenForProposals = 1,

**Comment by DCLHDEV** [comment]
Job Status Is Showing Published without validating Email.
==> Done. 

FYI, Email is not sending from a local machine. I have used the same code which is already there for registration to activating email. I just passed the jobId in email and updated the code on email verification page that if there is any JobId then I need to update the status of Job.
